app = "samachat-api"
primary_region = "iad"

[env]
  PORT = "3001"

[[services]]
  internal_port = 3001
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
